name: Romain Claret
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48203
title: 'Just me, a website about me...'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74600637-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010206'
    - '#e3f7fe'
    - '#00a8d7'
    - '#00407d'
    - '#0073b0'
  brandStrength: 0.9514796556904912
  lightness: 0.551188928540796
  saturation: 0.9405032575596124
  rhythmicContrast: 0.7406612164340913
purpose: []
