name: Romain Claret
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48203
title: "It's all about a guy named Romain..."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74600637-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0e2c6c'
    - '#185baa'
    - '#ccb9ab'
    - '#fffae7'
  brandStrength: 0.875
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
